### ISSUE TITLE
WiFi broken after reboot

### ISSUE THREAD

**Issue by aparcar** [Ansuel/openwrt#24]
### Describe the bug

This is a fake issue since OpenWrt is flawless :dia

### OpenWrt version

r23497-6637af95aa

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

Bananapi BPI-R3

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Ansuel** [comment]
@aparcar (for now reacts only on create events and not on edits)
